[package]
name = "gcprs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
itertools = "0.10.3"
ndarray = "0.15.0"
async-recursion = "0.2"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
hyper = "0.14"
hyper-rustls = "0.23"
yup-oauth2 = "^6.0"
rayon = "1.5"
urlencoding = "1.0.0"
webbrowser = "0.5"

tokio = { version = "1.18.0", features = ["full"] }

google-storage1 = { git = "https://github.com/tmokazaki/google-apis-rs.git" }
google-bigquery2 = { git = "https://github.com/tmokazaki/google-apis-rs.git", rev = "1cbca27" }
google-sheets4 = { git = "https://github.com/tmokazaki/google-apis-rs.git" }

[dev-dependencies]
speculate = "*"
rstest = "*"
