pub mod auth;
pub mod auth_legacy;
pub mod metadata;

#[cfg(feature = "aiplatform")]
pub mod aiplatform;
#[cfg(feature = "bigquery")]
pub mod bigquery;
pub mod common;
#[cfg(feature = "drive")]
pub mod drive;
#[cfg(feature = "gcs")]
pub mod gcs;
#[cfg(feature = "pubsub")]
pub mod pubsub;
#[cfg(feature = "run")]
pub mod run;
#[cfg(feature = "secretmanager")]
pub mod secretmanager;
#[cfg(feature = "sheets")]
pub mod sheets;
